FROM python:3.9-slim-buster
## named naxreo/python3.9:buster

COPY requirements.txt /requirements.txt
RUN set -eux; \
    apt-get update; \
    apt-get install -y git; \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install -r /requirements.txt && \
    pip3 cache purge && \
    rm -rf /tmp/* && \
    rm -rf ~/.cache/pip

CMD ["python3"]
